version: '3.4'

services:
  userservice.api:
    image: ${DOCKER_REGISTRY-}userserviceapi
    build:
      context: .
      dockerfile: UserService.Api/Dockerfile
    networks:
      - some-net  
    environment:
      - ASPNETCORE_URLS=http://*:5000
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
    - "5000:80" 
    depends_on:
    - "postgres"
    restart: on-failure
  rabbitmq: # login guest:guest
    image: rabbitmq:3-management
    hostname: rabbitmq
    labels:
      NAME: rabbitmq
    container_name: rabbitmq
    ports:
    - "4369:4369"
    - "5671:5671"
    - "5672:5672"
    - "25672:25672"
    - "15671:15671"
    - "15672:15672"
    networks:
      - some-net
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=UserServiceDb
    ports:
       - 5432:5432
    networks:
      - some-net   
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped
networks:
  some-net:
    driver: bridge